### ISSUE TITLE
Problem on install statisPages

### ISSUE THREAD

**Issue by mostaphazeghaouigmail** [tastyigniter/ti-ext-pages#1]
"SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 2 (SQL: insert into `ti_pages` (`content`, `date_added`, `date_updated`, `language_id`, `meta_description`, `meta_keywords`, `permalink_slug`, `status`, `title`) values (Lorem ipsum dolor sit amet, consectetur adipiscing elit., 2020-04-09 19:12:58, 2020-04-09 19:12:58, 1, , , about-us, 1, About Us), (Lorem ipsum dolor sit amet, consectetur adipiscing elit., 2020-04-09 19:12:58, 2020-04-09 19:12:58, 1, , , {"navigation_hidden":"1"}, policy, 1, Policy), (Lorem ipsum dolor sit amet, consectetur adipiscing elit., 2020-04-09 19:12:58, 2020-04-09 19:12:58, 1, , , terms-and-conditions, 1, Terms and Conditions))" on line 664 of /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php#0 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `ti...', Array, Object(Closure)) #1 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `ti...', Array, Object(Closure)) #2 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `ti...', Array) #3 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2646): Illuminate\Database\Connection->insert('insert into `ti...', Array) #4 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/extensions/igniter/pages/database/migrations/2018_06_28_000300_create_pages_table.php(82): Illuminate\Database\Query\Builder->insert(Array) #5 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/extensions/igniter/pages/database/migrations/2018_06_28_000300_create_pages_table.php(33): Igniter\Pages\Database\Migrations\CreatePagesTable->seedPages() #6 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(387): Igniter\Pages\Database\Migrations\CreatePagesTable->up() #7 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(396): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() #8 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(197): Illuminate\Database\Migrations\Migrator->runMigration(Object(Igniter\Pages\Database\Migrations\CreatePagesTable), 'up') #9 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(162): Illuminate\Database\Migrations\Migrator->runUp('/Users/user/www...', 1, false) #10 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(109): Illuminate\Database\Migrations\Migrator->runPending(Array, Array) #11 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/tastyigniter/flame/src/Database/Migrations/Migrator.php(14): Illuminate\Database\Migrations\Migrator->run('/Users/user/www...', Array) #12 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/system/classes/UpdateManager.php(237): Igniter\Flame\Database\Migrations\Migrator->run(Array) #13 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/system/models/Extensions_model.php(247): System\Classes\UpdateManager->migrateExtension('igniter.pages') #14 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/system/controllers/updates.php(357): System\Models\Extensions_model::install('igniter.pages', 'v1.3.1') #15 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/system/controllers/updates.php(335): System\Controllers\Updates->completeProcess(Array) #16 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/system/controllers/updates.php(191): System\Controllers\Updates->processInstallOrUpdate() #17 [internal function]: System\Controllers\Updates->browse_onProcess('browse', 'extensions') #18 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/admin/classes/AdminController.php(404): call_user_func_array(Array, Array) #19 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/admin/classes/AdminController.php(262): Admin\Classes\AdminController->runHandler('onProcess', Array) #20 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/admin/classes/AdminController.php(163): Admin\Classes\AdminController->processHandlers() #21 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/system/classes/Controller.php(105): Admin\Classes\AdminController->remap('browse', Array) #22 [internal function]: System\Classes\Controller->runAdmin('updates/browse/...') #23 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array) #24 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('runAdmin', Array) #25 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'runAdmin') #26 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController() #27 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Route->run() #28 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #29 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #30 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure)) #31 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #32 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/app/admin/middleware/LogUserLastSeen.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #33 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Admin\Middleware\LogUserLastSeen->handle(Object(Illuminate\Http\Request), Object(Closure)) #34 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #35 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(23): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #36 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure)) #37 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #38 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #39 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #40 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #41 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #42 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #43 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #44 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #45 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #46 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #47 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #48 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #49 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #50 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #51 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #52 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #53 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #54 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #55 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #56 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #57 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #58 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request)) #59 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #60 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/extensions/igniter/cart/middleware/CartMiddleware.php(10): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #61 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Cart\Middleware\CartMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure)) #62 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #63 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #64 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure)) #65 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #66 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #67 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #68 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #69 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #70 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #71 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #72 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #73 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #74 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #75 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #76 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #77 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #78 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #79 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #80 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #81 /Users/user/www/vhost/arcadia.com/www.bararcadia.com/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #82 {main}

**Comment by sampoyigi** [comment]
How can we reproduce this error?
